# Generated by Django 3.0.2 on 2020-01-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AGE', models.IntegerField()),
                ('SPORT', models.IntegerField()),
                ('WEIGHT', models.IntegerField()),
                ('HEIGHT', models.IntegerField()),
                ('label', models.FloatField()),
                ('zchest', models.FloatField()),
                ('zwrist', models.FloatField()),
                ('temp', models.FloatField()),
                ('activity', models.FloatField(null=True)),
            ],
        ),
    ]
